[package]
name = "hash-sig-testdata"

edition.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true
rayon.workspace = true

hash-sig-verifier.workspace = true

[lints]
workspace = true
