[package]
name = "sp1-script"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
