[package]
name = "hash-sig-testdata"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
hash-sig-verifier = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
