[package]
name = "hash-sig-testdata"

edition.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true }
hash-sig-verifier = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }

[lints]
workspace = true
