name: CI zkvm-openvm

defaults:
  run:
    working-directory: ./zkvm/openvm

on:
  pull_request:
    paths:
      - 'hash-sig/**'
      - 'zkvm/openvm/**'
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run instantiation keccak256
        run: cargo run -r --bin hash-sig-agg-zkvm-openvm-script -- -i keccak256 --size 1 --debug 1

      - name: Run instantiation poseidon2-baby-bear
        run: cargo run -r --bin hash-sig-agg-zkvm-openvm-script -- -i poseidon2-baby-bear --size 1 --debug 1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rust-docs, rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-features --all-targets
